export const projects = [
  {
    title: "Portfolio Project",
    id: "portfolio",
    subtitle: "This portfolio was created to showcase my projects using NextJS and Tailwindcss from scratch.",
    content: "This project is the website you are viewing right now. It was made using NextJS and Tailwindcss. This project was made from scratch and hosted on my own web domain.",
    cardImg: '/portfolio/portfolio-home.png',
    img1: "/portfolio/portfolio-home.png",
    img2: "/portfolio/portfolio-about.png",
    img3: "/portfolio/portfolio-project.png",
  }, 
  {
    title: "RunSignup Mobile Timer Application",
    id: "runSignupTimer",
    subtitle: "This project was a mobile application created for the company RunSingup.",
    content: "This project was created using REACT NATIVE along with the RunSignup API. This project was created for the company RunSignup. RunSignup wanted an application that can record times for their racing events using your mobile device, whether you have internet or not. The application is able to link the race you are recording to the RunSignup Database so the recorded times update on the spot during the race. If the user is offline, the app detects that and allows the user to upload after the device is connected to the internet. We also created a solution for their racer conflict problem that RunSignup specifically wanted us to address. There is further information on the poster we created that is linked below. The Github repository they use is public. The code has changed, however the base of the project was made by my group as well as another group.",
    cardImg: '/runSignup/runSignup-finishMode.png',
    img1: "/runSignup/runSignup-finishModeCropped.png",
    img2: "/runSignup/runSignup-chuteModeCropped.png",
    img3: "/runSignup/runSignup-resultsModeCropped.png",
  },
  {
    title: "Salty",
    id: "salty",
    subtitle: "This is a project that me and 5 other developers created that is able to record a users voice and interpret their emotion based on their volume tendencies.",
    content: 'The "Salty" application is a desktop application created by me and 5 other developers using Electron, React, PostgreSQL, Javascript, Python, and CSS. The application was focused more on functionality rather than appearance due to our professor emphasizing functionality over appearance and our limited timeframe. This application records a users voice and interprets their emotion stage based on their volume tendencies while playing video games. The application gives the user a score from 1 - 1000 during each recording session. The user selects the game they want to play and starts recording before their gaming session. If their game is not available they can manually add it. Once their session has completed and the user has stopped recording, the application will generate a score and log it in our database for the user and for the game they played. We also created leaderboards so the user can see their statistics for each game they play and you can view the people with the highest score for each game.',
    cardImg: '/salty/salty-home.png',
    img1: "/salty/salty-home.png",
    img2: "/salty/salty-login.png",
    img3: "/salty/salty-users.png",
    img4: "/salty/salty-record.png",
    img5: "/salty/salty-game.png",
  },
  // {
  //   title: "Secret Spots!",
  //   id: "nationalParks",
  //   subtitle: "A small project I created using NextJS that utilizes the NPS API to help users find places to visit while on a trip.",
  //   content: "A small project I created using NextJS that utilizes the NPS API to help users find places to visit while on a trip.",
  //   cardImg: `/nationalParks/nationalParks-homePage.png`,
  //   img1: `/nationalParks/nationalParks-homePage.png`,
  //   img2: "/nationalParks/nationalParks-resultsPage.png", 
  // }, 
  
]